//! The shipped tables, generated from the crate's own `themes/` and
//! `palettes/`: the shipped set is the directory, not a list (see `AGENTS.md`).
//! Each file is embedded with `include_str!`, so the binary carries its own
//! copies to write out on a machine that has never seen them.
//!
//! Everything that can fail fails the build, by file and field.

use std::fmt::Write as _;
use std::{env, fs, path::Path};

fn main() {
    write_built_in_table("themes", "built_in.rs", check);
    write_built_in_table("palettes", "built_in_palettes.rs", check_palette);
    // See `winresource` in `Cargo.toml`.
    #[cfg(windows)]
    if env::var("CARGO_CFG_TARGET_OS").as_deref() == Ok("windows") {
        println!("cargo:rerun-if-changed=icons/icon.ico");
        winresource::WindowsResource::new()
            .set_icon("icons/icon.ico")
            // What Windows calls the app — Search, Task Manager, "Open
            // with". Both default to the crate's name, which is lower case.
            .set("FileDescription", "Moonowl")
            .set("ProductName", "Moonowl")
            .compile()
            .expect("icons/icon.ico could not be compiled into the executable");
    }
}

/// The colour fields a theme may carry, all of which must be hex if they are
/// there at all. Kept in step with `Theme` in `theme.rs`, and with
/// `read_colour`, which decides at runtime whether a colour can be read.
const COLORS: &[&str] = &[
    "text",
    "background",
    "accent",
    "link",
    "selection_area",
    "selection_text",
    "ground",
];

/// Generate a `BUILT_IN` table from a directory of the crate's own rather
/// than from a list somebody has to remember to edit: `themes/` into
/// `built_in.rs`, `palettes/` into `built_in_palettes.rs`.
fn write_built_in_table(folder: &str, target: &str, check: fn(&str, &str) -> i64) {
    let dir = Path::new(env!("CARGO_MANIFEST_DIR")).join(folder);
    println!("cargo:rerun-if-changed={folder}");
    println!("cargo:rerun-if-changed=build.rs");

    let mut kept: Vec<(i64, String)> = Vec::new();
    for entry in fs::read_dir(&dir)
        .unwrap_or_else(|e| panic!("{folder}/: {e}"))
        .flatten()
    {
        let path = entry.path();
        if path.extension().and_then(|e| e.to_str()) != Some("toml") {
            continue;
        }
        let id = path
            .file_stem()
            .and_then(|s| s.to_str())
            .expect("file name")
            .to_string();
        let source =
            fs::read_to_string(&path).unwrap_or_else(|e| panic!("{folder}/{id}.toml: {e}"));
        kept.push((check(&id, &source), id));
    }

    kept.sort();
    for pair in kept.windows(2) {
        assert!(
            pair[0].0 != pair[1].0,
            "{folder}/{}.toml and {folder}/{}.toml both claim order {}",
            pair[0].1,
            pair[1].1,
            pair[0].0,
        );
    }

    let mut out = format!(
        "/// What ships with Moonowl, in the order it is listed in, generated by\n\
         /// `build.rs` from the contents of `{folder}/`.\n\
         pub const BUILT_IN: &[(&str, &str)] = &[\n"
    );
    for (_, id) in &kept {
        let _ = writeln!(
            out,
            "    ({id:?}, include_str!(concat!(env!(\"CARGO_MANIFEST_DIR\"), \"/{folder}/{id}.toml\"))),"
        );
    }
    out.push_str("];\n");

    let target = Path::new(&env::var("OUT_DIR").expect("OUT_DIR")).join(target);
    fs::write(&target, out).expect("write the built-in table");
}

/// Check one shipped palette and return the order it asked for: a name, an
/// order, and six colours `read_colour` can read.
fn check_palette(id: &str, source: &str) -> i64 {
    let table: toml::Table = source
        .parse()
        .unwrap_or_else(|e| panic!("palettes/{id}.toml is not readable TOML: {e}"));
    for key in table.keys() {
        assert!(
            ["name", "order", "colors"].contains(&key.as_str()),
            "palettes/{id}.toml: `{key}` is not a key a palette has"
        );
    }
    assert!(
        table
            .get("name")
            .and_then(|v| v.as_str())
            .is_some_and(|n| !n.trim().is_empty()),
        "palettes/{id}.toml has no name",
    );
    let colors = table
        .get("colors")
        .and_then(|v| v.as_array())
        .unwrap_or_else(|| panic!("palettes/{id}.toml has no `colors` list"));
    assert!(
        colors.len() == 6,
        "palettes/{id}.toml has {} colors, not six",
        colors.len()
    );
    for colour in colors {
        assert!(
            colour.as_str().is_some_and(is_hex),
            "palettes/{id}.toml: {colour} is not a colour the renderer can read",
        );
    }
    table
        .get("order")
        .and_then(|v| v.as_integer())
        .unwrap_or_else(|| panic!("palettes/{id}.toml has no `order`"))
}

/// Check one shipped theme and return the order it asked for.
fn check(id: &str, source: &str) -> i64 {
    let table: toml::Table = source
        .parse()
        .unwrap_or_else(|e| panic!("themes/{id}.toml is not readable TOML: {e}"));

    // Every key one `Theme` reads, of the type it reads it as: a shipped file
    // that builds and then does not parse is dropped from the menu at run
    // time, and a misspelt key is a colour silently derived.
    for (key, value) in &table {
        let fits = match key.as_str() {
            "name" | "selection" => value.is_str(),
            "recolor" => value.is_bool(),
            "order" => value.is_integer(),
            other if COLORS.contains(&other) => value.is_str(),
            other => panic!("themes/{id}.toml: `{other}` is not a key a theme has"),
        };
        assert!(
            fits,
            "themes/{id}.toml: `{key}` is {value}, of the wrong type"
        );
    }

    let name = table.get("name").and_then(|v| v.as_str());
    assert!(
        name.is_some_and(|n| !n.trim().is_empty()),
        "themes/{id}.toml has no name",
    );

    for field in COLORS {
        let Some(value) = table.get(*field) else {
            assert!(
                *field != "text" && *field != "background",
                "themes/{id}.toml has no {field}",
            );
            continue;
        };
        let colour = value
            .as_str()
            .unwrap_or_else(|| panic!("themes/{id}.toml: {field} is not a string"));
        assert!(
            is_hex(colour),
            "themes/{id}.toml: {field} is {colour:?}, which the renderer cannot read — \
             colours are #abc, #abcd, #aabbcc or #aabbccdd and nothing else",
        );
    }

    table
        .get("order")
        .and_then(|v| v.as_integer())
        .unwrap_or_else(|| {
            panic!("themes/{id}.toml has no `order`, so nothing knows where to list it")
        })
}

/// The same alphabet and the same four lengths `parseColor` accepts.
fn is_hex(colour: &str) -> bool {
    let Some(digits) = colour.strip_prefix('#') else {
        return false;
    };
    matches!(digits.len(), 3 | 4 | 6 | 8) && digits.bytes().all(|b| b.is_ascii_hexdigit())
}
