//! The shipped theme table, generated from the app's own `themes/` directory.
//!
//! This is `src-tauri/build.rs` with `tauri_build::build()` taken off the top
//! and the directory pointed at the app's rather than at one of its own. There
//! is no copy of the fourteen themes in this crate and there must not be: a
//! second copy of a theme file is the drift `build.rs` was written to remove
//! (see "And the shipped set is the directory, not a list" in `AGENTS.md`),
//! and it would drift here in exactly the way it drifted between `theme.rs`
//! and `api.ts`.
//!
//! Everything that can fail still fails the build, by file and field.

use std::fmt::Write as _;
use std::{env, fs, path::Path, path::PathBuf};

fn main() {
    write_built_in_table();
    // See `winresource` in `Cargo.toml`.
    #[cfg(windows)]
    if env::var("CARGO_CFG_TARGET_OS").as_deref() == Ok("windows") {
        println!("cargo:rerun-if-changed=icons/icon.ico");
        winresource::WindowsResource::new()
            .set_icon("icons/icon.ico")
            .compile()
            .expect("icons/icon.ico could not be compiled into the executable");
    }
}

/// Where the app keeps the themes this crate ships.
fn themes_dir() -> PathBuf {
    Path::new(env!("CARGO_MANIFEST_DIR")).join("themes")
}

/// The colour fields a theme may carry, all of which must be hex if they are
/// there at all. Kept in step with `Theme` in `theme.rs` and with `parseColor`
/// in `themes.ts`, which is the function that decides at runtime whether a
/// colour can be read.
const COLORS: &[&str] = &[
    "text",
    "background",
    "accent",
    "link",
    "selection_area",
    "selection_text",
];

/// Generate the `BUILT_IN` table from the directory rather than from a list
/// somebody has to remember to edit.
fn write_built_in_table() {
    let dir = themes_dir();
    println!("cargo:rerun-if-changed=themes");
    println!("cargo:rerun-if-changed=build.rs");

    let mut themes: Vec<(i64, String)> = Vec::new();
    for entry in fs::read_dir(&dir)
        .expect("the app's themes directory")
        .flatten()
    {
        let path = entry.path();
        if path.extension().and_then(|e| e.to_str()) != Some("toml") {
            continue;
        }
        let id = path
            .file_stem()
            .and_then(|s| s.to_str())
            .expect("theme file name")
            .to_string();
        let source = fs::read_to_string(&path).unwrap_or_else(|e| panic!("themes/{id}.toml: {e}"));
        themes.push((check(&id, &source), id));
    }

    themes.sort();
    for pair in themes.windows(2) {
        assert!(
            pair[0].0 != pair[1].0,
            "themes/{}.toml and themes/{}.toml both claim order {}",
            pair[0].1,
            pair[1].1,
            pair[0].0,
        );
    }

    let mut out = String::from(
        "/// The themes that ship with Moonowl, in the order they are listed in,\n\
         /// generated by `build.rs` from the contents of the app's `themes/`.\n\
         pub const BUILT_IN: &[(&str, &str)] = &[\n",
    );
    for (_, id) in &themes {
        let _ = writeln!(
            out,
            "    ({id:?}, include_str!(concat!(env!(\"CARGO_MANIFEST_DIR\"), \"/themes/{id}.toml\"))),"
        );
    }
    out.push_str("];\n");

    let target = Path::new(&env::var("OUT_DIR").expect("OUT_DIR")).join("built_in.rs");
    fs::write(&target, out).expect("write the built-in theme table");
}

/// Check one shipped theme and return the order it asked for.
fn check(id: &str, source: &str) -> i64 {
    let table: toml::Table = source
        .parse()
        .unwrap_or_else(|e| panic!("themes/{id}.toml is not readable TOML: {e}"));

    let name = table.get("name").and_then(|v| v.as_str());
    assert!(
        name.is_some_and(|n| !n.trim().is_empty()),
        "themes/{id}.toml has no name",
    );

    for field in COLORS {
        let Some(value) = table.get(*field) else {
            assert!(
                *field != "text" && *field != "background",
                "themes/{id}.toml has no {field}",
            );
            continue;
        };
        let colour = value
            .as_str()
            .unwrap_or_else(|| panic!("themes/{id}.toml: {field} is not a string"));
        assert!(
            is_hex(colour),
            "themes/{id}.toml: {field} is {colour:?}, which the renderer cannot read — \
             colours are #abc, #abcd, #aabbcc or #aabbccdd and nothing else",
        );
    }

    table
        .get("order")
        .and_then(|v| v.as_integer())
        .unwrap_or_else(|| {
            panic!("themes/{id}.toml has no `order`, so nothing knows where to list it")
        })
}

/// The same alphabet and the same four lengths `parseColor` accepts.
fn is_hex(colour: &str) -> bool {
    let Some(digits) = colour.strip_prefix('#') else {
        return false;
    };
    matches!(digits.len(), 3 | 4 | 6 | 8) && digits.bytes().all(|b| b.is_ascii_hexdigit())
}
