//! **The port, judged against the app rather than against somebody's memory
//! of it.**
//!
//! Every interface fault the reader reported was found by using the two side
//! by side, which is a slow way to find one fault at a time. This file is the
//! fast way to find all of them: `tests/parity/app-inventory.json` was taken
//! from the *running Tauri app*, in WebKit, through its own UI harness —
//! what each toolbar group holds, what each menu lists in what order, what the
//! sidebar's tabs are called, and what all twenty-two of `applyTheme`'s
//! custom properties resolve to. The assertions below read that file and ask
//! the port the same questions.
//!
//! **The fixture is frozen.** It was regenerated by driving the running Tauri
//! app through `scripts/ui-harness.mjs`; that app is retired and the script is
//! gone with it, so these numbers stop being "what the app does" and become
//! what this interface *is*. Changing one is now a decision, taken here.
//!
//! What this file cannot cover is anything about the *window* — dragging it,
//! full screen, the traffic lights — and anything the app drew with a browser
//! widget the renderer has no counterpart for; those are named where they
//! occur.

use moonowl::harness::{Options, Reader};
use serde_json::Value;

/// Two pixels on macOS, where the fixture was taken, and a typeface's worth of
/// room anywhere else.
///
/// The numbers in `app-inventory.json` came out of WebKit on the machine this
/// was written on, where `ui-sans-serif` is SF Pro. A Windows runner resolves
/// that stack to Segoe UI and a Linux one to DejaVu Sans; the first sets the
/// same words a couple of per cent narrower and the second several per cent
/// wider, and no CSS makes a different typeface measure the same. So off macOS
/// the allowance is proportional — the error is in the *type*, so it grows
/// with how much of it is in the box: six pixels on a chip, ten on the start
/// screen's Open button, which carries the longest label in the interface.
/// What is still being asserted is that the arrangement is the app's.
fn slack(want: f64) -> f64 {
    if cfg!(target_os = "macos") {
        2.0
    } else {
        (want.abs() * 0.06).max(6.0)
    }
}

fn app() -> Value {
    let raw = include_str!("parity/app-inventory.json");
    serde_json::from_str(raw).expect("the app's inventory")
}

fn reader() -> Reader {
    // The size the fixture was taken at, because a bar that has run out of
    // room drops things out of it.
    Reader::open_with(
        &Reader::book(),
        Options {
            width: 1280,
            height: 860,
            system_font: cfg!(target_os = "macos"),
            ..Default::default()
        },
    )
}

/// Labels out of a list of inventory rows, skipping what has no words.
fn labels(rows: &Value) -> Vec<String> {
    rows.as_array()
        .expect("rows")
        .iter()
        .filter_map(|row| row.get("label").and_then(Value::as_str))
        .filter(|label| !label.is_empty())
        .map(str::to_string)
        .collect()
}

/// **The toolbar holds what the app's holds, in the app's order.**
///
/// By the words on each control, because that is what a reader sees. The
/// icon-only ones — the page arrows, the two ends of the zoom group — have no
/// words and are counted by the group's length instead.
#[test]
fn the_toolbar_says_what_the_app_s_says() {
    let reader = reader();
    let app = app();
    for (group, selector) in [
        ("bar-left", ".bar-left"),
        ("bar-center", ".bar-center"),
        ("bar-right", ".bar-right"),
    ] {
        let kept: Vec<Value> = app["toolbar"][group]
            .as_array()
            .expect("rows")
            .iter()
            .filter(|row| {
                !row.get("id")
                    .and_then(Value::as_str)
                    .is_some_and(|id| MOVED.contains(&id))
            })
            .cloned()
            .collect();
        let want = labels(&Value::Array(kept));
        let got: Vec<String> = reader
            .text_all(&format!("{selector} button, {selector} .of"))
            .into_iter()
            .filter(|label| !label.is_empty())
            .collect();
        assert_eq!(got, want, "{group}");
    }
}

/// **And it is the same size as the app's, control for control.**
///
/// This is the one measurement in the file, and it is here because it is the
/// only question that can see the *type*. A chip is its padding plus its icon
/// plus its word; the padding and the icon are numbers both readers already
/// agree on, so what is left over is the word, and the word is the font. The
/// port's every chip came out about five per cent narrow — `Contents` 96
/// against 101.3, `of 400` 38 against 41.5 — because parley does not read SF's
/// `trak` table and WebKit does, so the system font arrived with its
/// small-size tracking missing. Nothing that compares *labels* could have said
/// so, and what a reader saw was a bar that was tighter and darker than the
/// app's without being able to name what had changed. See `body` in
/// `styles.rs`.
///
/// Two pixels of tolerance, and it has to be that loose: the app's numbers
/// are fractional and Blitz rounds a box to whole pixels, so 101.3 can only
/// ever come back as 101.
#[test]
fn the_toolbar_is_the_size_of_the_app_s() {
    let reader = reader();
    let app = app();
    // The middle group, whole. The two sides hold the same controls at the
    // same widths — which is what is asserted below — but where they *end* is
    // the flex arrangement, and that is deliberately not the app's: see
    // `.bar-left` in `styles.rs` on why the bases are nought here and `auto`
    // there.
    let want = app["toolbar"]["bar-center-box"]["width"]
        .as_f64()
        .expect("the middle group's width");
    let got = reader.width_of(".bar-center").expect("the middle group");
    assert!(
        (got - want).abs() <= slack(want),
        "the middle group is {got} wide and the app's is {want}",
    );

    // Every control that carries a word, by the class this reader gives it.
    // The icon-only ones are left out on purpose: a square is a square in
    // both readers and says nothing about the type.
    for (id, selector) in [
        ("contents", ".chip.contents"),
        ("close-doc", ".chip.close-doc"),
        ("doc-title", ".chip.title"),
        ("page-count", ".of"),
        ("find", ".chip.find"),
        ("zoom-level", ".chip.fit"),
    ] {
        let want = app["toolbar"]
            .as_object()
            .expect("the toolbar")
            .values()
            .filter_map(Value::as_array)
            .flatten()
            .find(|row| row.get("id").and_then(Value::as_str) == Some(id))
            .and_then(|row| row.get("width"))
            .and_then(Value::as_f64)
            .unwrap_or_else(|| panic!("no {id} in the inventory"));
        let got = reader
            .width_of(selector)
            .unwrap_or_else(|| panic!("no {selector}"));
        assert!(
            (got - want).abs() <= slack(want),
            "{id} is {got} wide and the app's is {want}"
        );
    }
}

/// **And the surfaces that float or list are the size the app's are.**
///
/// The widths above catch the type in the toolbar; this catches it everywhere
/// else, and by height rather than by width for the same reason: a row is its
/// padding plus its line, both readers agree about the padding, so the height
/// is the type. Every one of these was a row shorter — a menu item 30 against
/// 35, a tab 26 against 28, a switch 23 against 20 — because the port wrote
/// its menus, its sidebar and its Settings window in the toolbar's 13.5 where
/// `.popover`, `#sidebar` and `.window` each say 14.5. Which is not a thing
/// any comparison of *labels* can see, and the reader who reported it could
/// only say that the port looked smaller.
#[test]
fn the_surfaces_are_the_size_of_the_app_s() {
    let app = app();
    let want = |name: &str| app["rows"][name].as_f64();

    // A menu, open. Theme is the one every reader sees.
    let mut menu = reader();
    menu.click(".chip.theme");
    for (name, selector) in [
        ("menu-item", ".menu-item"),
        ("menu-heading", ".menu-section"),
    ] {
        let Some(tall) = want(name) else { continue };
        assert!(menu.harness.query(selector).is_some(), "no {selector}");
        let got = menu.harness.layout_rect(selector).height as f64;
        assert!(
            (got - tall).abs() <= slack(tall),
            "{name} is {got} tall and the app's is {tall}",
        );
    }

    // The sidebar's tab strip.
    let mut panel = reader();
    panel.press_chord("mod+b");
    let tab = panel.harness.layout_rect(".tab").height as f64;
    let wanted = want("tab").expect("the app's tab");
    assert!(
        (tab - wanted).abs() <= slack(wanted),
        "a tab is {tab} tall and the app's is {wanted}"
    );

    // And the Settings window.
    let mut window = reader();
    window.press_chord("mod+,");
    for (name, selector) in [
        ("window-bar", ".window-bar"),
        ("nav-item", ".nav-item"),
        ("switch", ".switch"),
    ] {
        let Some(tall) = want(name) else { continue };
        let got = window.harness.layout_rect(selector).height as f64;
        assert!(
            (got - tall).abs() <= slack(tall),
            "{name} is {got} tall and the app's is {tall}",
        );
    }
}

/// Every menu the toolbar opens, item for item and rule for rule.
///
/// The app's own five: Open, the document's name, the zoom readout, Theme and
/// the cog. A rule is a row in this comparison because where the rules fall is
/// half of what a menu reads like.
/// **What this port has that the app does not, named here rather than
/// tolerated.**
///
/// A port that quietly grew items would be a port whose parity claim means
/// nothing, so the exceptions are a list — the same arrangement
/// `keymap::EXTRA` has for the three keyboard actions this reader has and the
/// app has not. Two: signing — see `src/sign.rs`, and `signing-assessment.md`
/// for the two things that word means and which of them this is — and one
/// zoom preset. 175% is a step on `ZOOM_LADDER` that ⌘+ walks through in both
/// and that neither menu offered, so reaching it took the stepper or a count
/// of key presses; it was asked for, and the app's own ladder already says it
/// is a size somebody reads at.
///
/// Adding a row here is a decision. Anything not in it is drift.
///
/// The third is "New tab", and it is on this list rather than in the fixture
/// because the app had nothing to put there: it ran in a webview, where a
/// window is a window. Here macOS turns a new window into a tab of its own
/// accord while the app is full screen, and turning that off — which is what
/// ⌘N being a window requires — leaves the reader no way to ask for the tab
/// they were being given. See `tabs.rs`. It is macOS's alone, so off that
/// platform there is nothing to filter and the row simply is not drawn.
const OURS: [(&str, &str); 6] = [
    ("document", "Sign…"),
    ("settings", "Present"),
    ("view", "175%"),
    ("open", "New tab"),
    ("view", "Rotate left"),
    ("view", "Rotate right"),
];

/// **Where the port says it differently, on purpose**: the app's words, and
/// the port's. "Mark" meant a bookmark in one menu and a highlight in the
/// next, and the Information item opened a window called something else.
/// Mapped here rather than written into the fixture, for `OURS`'s reason.
const RENAMED: [(&str, &str); 2] = [
    ("Mark this page", "Bookmark this page"),
    ("Document", "Information"),
];

fn renamed(label: String) -> String {
    RENAMED
        .iter()
        .find(|(app, _)| *app == label)
        .map_or(label, |(_, ours)| ours.to_string())
}

/// **What the app kept in its toolbar and the port keeps in a menu**: the
/// two rotations, rare enough that their room in the bar was better spent on
/// keeping every other control's words. They are in the View menu — see
/// `OURS`.
const MOVED: [&str; 2] = ["rotate-left", "rotate-right"];

#[test]
fn every_menu_lists_what_the_app_s_lists() {
    let mut reader = reader();
    let app = app();
    for (chip, menu, id) in [
        (".chip.open", "open", "open"),
        (".chip.title", "document", "doc-title"),
        (".chip.fit", "view", "zoom-level"),
        (".chip.theme", "theme", "theme"),
        (".chip.settings", "settings", "settings"),
    ] {
        // The app writes a rule as a row of its own and this reader writes it
        // as an empty `.menu-rule`, so both sides are read as "label, or
        // nothing" and compared in order.
        let want: Vec<String> = app["menus"][id]
            .as_array()
            .unwrap_or_else(|| panic!("no {id} menu in the inventory"))
            .iter()
            .map(|row| {
                row.get("label")
                    .and_then(Value::as_str)
                    .unwrap_or_default()
                    // The app puts the shortcut inside the row it belongs to;
                    // this reader puts it in a span of its own. Compare the
                    // words, not the chord — `tests/keys.rs` is where chords
                    // are checked, against `keys.ts`.
                    .split('⌘')
                    .next()
                    .unwrap_or_default()
                    .trim()
                    .to_string()
            })
            .collect();
        // The fixture was taken on macOS and says "Show in Finder"; the app
        // names the platform's own file manager there and so does the port,
        // which is a difference between machines rather than between the two.
        let want: Vec<String> = want
            .into_iter()
            .map(|label| label.replace("Finder", moonowl::app::file_manager_name()))
            .map(renamed)
            .collect();
        reader.click(chip);
        let got: Vec<String> = reader
            .text_all(&format!(
                ".menu.{menu} .menu-label, .menu.{menu} .menu-row-label, \
                 .menu.{menu} .menu-section, .menu.{menu} .menu-rule"
            ))
            .into_iter()
            // The port's own, taken out before the comparison rather than
            // written into the fixture: the fixture is what the *app* holds,
            // and editing it to say otherwise would be the copy going stale in
            // the one direction nothing could see. See `OURS`.
            .filter(|label| !OURS.contains(&(menu, label.as_str())))
            .collect();
        assert_eq!(got, want, "the {menu} menu");
        reader.press("Escape");
    }
}

/// The sidebar's tabs. Results is hidden until something has been searched
/// for, in both, which is why there are two here and not three.
#[test]
fn the_sidebar_has_the_app_s_tabs() {
    let mut reader = reader();
    let want = labels(&app()["sidebar"]);
    reader.click(".chip.contents");
    assert_eq!(reader.text_all(".tab"), want);
}

/// **Every colour the chrome is built from, against the app's own.**
///
/// `applyTheme` writes twenty-two custom properties onto the root and this
/// reader writes the same values under names of its own; the pairs are below.
/// They were all near-misses of the app's arithmetic — a surface pulled 6%
/// towards the ink where the app pulls it 55% towards white — which is the
/// kind of difference nobody can name from a screenshot and every one of
/// these catches.
#[test]
fn the_theme_resolves_to_the_app_s_colours() {
    let reader = reader();
    let app = app();
    let style = reader.harness.attr(".root", "style").unwrap_or_default();
    let of = |name: &str| {
        style
            .split(';')
            .filter_map(|entry| entry.split_once(':'))
            .find(|(key, _)| key.trim() == name)
            .map(|(_, value)| value.trim().to_string())
            .unwrap_or_else(|| panic!("no {name} on the root"))
    };
    for (theirs, ours) in [
        ("--bg", "--ground"),
        ("--surface", "--surface"),
        ("--surface-hover", "--hover"),
        ("--surface-sunk", "--sunk"),
        ("--line", "--line"),
        ("--text", "--text"),
        ("--text-soft", "--muted"),
        ("--text-note", "--note"),
        // Not "--text-faint": the app's was 2.7:1 on its own paper, for words
        // meant to be read, and the port's comes back towards the ink until
        // it is 3:1. See `Palette::faint`.
        ("--accent", "--accent"),
        ("--accent-soft", "--accent-soft"),
        ("--accent-contrast", "--accent-contrast"),
        ("--positive", "--positive"),
        ("--negative", "--negative"),
        ("--negative-contrast", "--negative-contrast"),
        ("--page-paper", "--page"),
        ("--bar-hover", "--bar-hover"),
        ("--bar-sunk", "--bar-sunk"),
        ("--bar-line", "--bar-line"),
        ("--bar-accent", "--bar-accent"),
        ("--selection-area", "--found"),
        ("--selection-text", "--found-ink"),
    ] {
        let want = app["theme"][theirs].as_str().expect(theirs);
        assert_eq!(of(ours), want, "{ours} against the app's {theirs}");
    }
}

/// The Settings window: the pages it has, the fields on each in order, the
/// headings between them, and the buttons at the foot.
///
/// This is the largest surface in the app and the least looked at, which is
/// exactly why it is here: the theme editor was missing entirely, "Recolour
/// pictures too" was on the wrong page, and Full screen and Presenting were a
/// sentence rather than two switches.
#[test]
fn the_settings_window_has_the_app_s_pages() {
    let mut reader = reader();
    let app = app();
    let settings = &app["settings"];

    reader.press_chord("mod+,");
    let nav: Vec<String> = settings["nav"]
        .as_array()
        .expect("nav")
        .iter()
        .map(|name| name.as_str().unwrap_or_default().to_string())
        .collect();
    assert_eq!(reader.text_all(".nav-item"), nav, "the pages themselves");

    for (at, page) in nav.iter().enumerate() {
        reader.click_nth(".nav-item", at);
        let want = &settings["pages"][page];
        let list = |key: &str| -> Vec<String> {
            want[key]
                .as_array()
                .unwrap_or_else(|| panic!("{page} has no {key}"))
                .iter()
                .map(|row| row.as_str().unwrap_or_default().to_string())
                // Tabs are macOS's alone, and so is the switch for them.
                .filter(|row| cfg!(target_os = "macos") || row != "Open documents in tabs")
                .collect()
        };
        assert_eq!(
            reader.text_all(".field-label"),
            list("fields"),
            "{page}: fields"
        );
        assert_eq!(
            reader.text_all(".pane-group"),
            list("groups"),
            "{page}: headings"
        );
        assert_eq!(
            reader.text_all(".pane-actions button"),
            list("actions"),
            "{page}: buttons",
        );
    }
}

/// The find bar's three switches, which are the only words in it — everything
/// else there is an icon.
#[test]
fn the_find_bar_offers_the_app_s_three_switches() {
    let mut reader = reader();
    let want = labels(&app()["find"]["rows"]);
    reader.press_chord("mod+f");
    assert_eq!(reader.text_all(".find-option"), want);
}

/* ---------------------------------------------------------------------------
 *
 * The four surfaces the fixture used not to reach.
 *
 * Everything above was taken from the toolbar and the windows a reader opens
 * from it, which is most of the app and is not all of it. What follows is the
 * screen with no document on it, the window the title menu's last item opens,
 * the theme editor, and the three things the app says on top of a page. Each
 * was invisible to this file until the inventory was widened to take it, which
 * is the argument for widening it: a surface nothing compares is a surface
 * that drifts.
 */

/// **The start screen says what the app's says.**
///
/// The four lines of it, and what the recents shelf is called. This is the
/// first thing anybody sees and it had never been compared — the port could
/// have been calling itself anything.
#[test]
fn the_start_screen_reads_like_the_app_s() {
    let reader = Reader::empty(Options {
        width: 1280,
        height: 860,
        system_font: cfg!(target_os = "macos"),
        ..Default::default()
    });
    let app = app();
    let start = &app["start"];
    let want = |key: &str| start[key].as_str().unwrap_or_default().to_string();
    let one = |selector: &str| {
        reader
            .text_all(selector)
            .first()
            .cloned()
            .unwrap_or_default()
    };

    assert_eq!(one(".start-name"), want("name"), "the name");
    assert_eq!(one(".start-sub"), want("sub"), "the line under it");
    assert_eq!(one(".start-open"), want("open"), "the button");
    assert_eq!(one(".start-hint"), want("hint"), "the hint at the foot");
}

/// **And it is laid out and coloured the way the app's is.**
///
/// The four lines above all matched while the screen was wrong in three ways
/// at once, which is the argument for this test: a reader who looked at the
/// two side by side could say the button was too wide, the ground was the
/// wrong colour and the names in the shelf were spaced oddly, and nothing
/// that compares *words* could see any of it.
///
/// What each number here catches:
///
/// - *The ground.* `#welcome` is `--bg`, the shade a page floats on, because
///   the start screen stands where the document will. This was `--paper` —
///   the toolbar's own colour — so the window changed shade the moment
///   anything was opened, and the screen read as one flat panel with the bar.
/// - *The type.* `#welcome` sets 14.5px, the way `.popover`, `#sidebar` and
///   `.window` do; this was the body's 13.5, which is the same fault the
///   three of them had and this the fourth surface with it. The button's
///   width is what says so — padding plus icon plus gap plus the word — and
///   the shelf's row height is the other half, being padding plus a line.
/// - *The button.* 100% of the column against the app's 176: a band across
///   the screen where the app has a button the width of its own words.
///
/// The ground is read off the *pixels* rather than off a stylesheet, because
/// a colour named correctly and painted by something else on top is still the
/// wrong colour on screen. A point in the left margin, well clear of the
/// 460px column in the middle of it.
#[test]
fn the_start_screen_is_laid_out_like_the_app_s() {
    let mut reader = Reader::empty(Options {
        width: 1280,
        height: 860,
        system_font: cfg!(target_os = "macos"),
        ..Default::default()
    });
    let app = app();
    let start = &app["start"];

    // The fixture's own two answers agree, which is what makes the assertion
    // below a comparison and not a number written down twice.
    assert_eq!(
        start["background"], app["theme"]["--bg"],
        "the app's start screen is its `--bg`",
    );

    let want = start["background"].as_str().expect("the app's ground");
    let shot = reader.screenshot();
    let pixel = shot.at(shot.width / 20, shot.height * 3 / 4);
    let got = format!("#{:02x}{:02x}{:02x}", pixel[0], pixel[1], pixel[2]);
    assert_eq!(got, want, "the ground the start screen stands on");

    for (name, selector) in [("open", ".start-open"), ("inner", ".start-inner")] {
        let box_of = |key: &str| start["boxes"][name][key].as_f64();
        let (_, _, width, height) = reader
            .box_of(selector)
            .unwrap_or_else(|| panic!("no {selector}"));
        // Width alone for the column, which is `min(460px, 82vw)` in both and
        // whose *height* is the sum of everything in it — a number that says
        // nothing on its own and would fail for whichever part of it moved.
        let wanted = box_of("width").expect("a width");
        // The same two pixels every other measured control gets. It was three
        // for a while, to carry the 2.9px the flat `letter-spacing` left on
        // this button — the longest label in the interface, so the one that
        // showed it worst. Setting the font's optical size instead took that
        // to 0.1px and the allowance went back with it.
        assert!(
            (width as f64 - wanted).abs() <= slack(wanted),
            "{name} is {width} wide and the app's is {wanted}",
        );
        if let Some(wanted) = box_of("height").filter(|_| name == "open") {
            assert!(
                (height as f64 - wanted).abs() <= slack(wanted),
                "{name} is {height} tall and the app's is {wanted}",
            );
        }
    }
}

/// **A row of the recents shelf is the height of the app's.**
///
/// Separate from the test above because it needs a shelf, and a shelf needs a
/// library: `Reader::empty` opens on a fresh config directory with nothing
/// read yet. The app's own number is measured rather than stated — see the
/// probe in `take-inventory.mjs` — because the browser fallback's `bootstrap`
/// hands the harness no library at all and the row therefore has to be built
/// out of the app's own cascade.
///
/// It was 34 against 37, which is 8px of padding either side of a line of
/// 1.45 × 13.5 where the app has 1.45 × 14.5. Six rows of it is a shelf a
/// fifth of a row short, which is exactly the sort of difference a reader
/// notices and cannot name.
#[test]
fn a_recents_row_is_the_height_of_the_app_s() {
    let app = app();
    let want = app["start"]["boxes"]["recent"]["height"]
        .as_f64()
        .expect("the app's row");
    // A config directory of its own, a document read in it, and the document
    // put down again — which is the only way to a shelf with something on it,
    // there being no seam for seeding one.
    let dir = std::env::temp_dir().join(format!("moonowl-parity-shelf-{}", std::process::id()));
    let _ = std::fs::remove_dir_all(&dir);
    let mut reader = Reader::open_with(
        &Reader::book(),
        Options {
            width: 1280,
            height: 860,
            config: dir,
            system_font: cfg!(target_os = "macos"),
            ..Default::default()
        },
    );
    reader.click("[data-item=\"close-document\"]");
    let (_, _, _, height) = reader.box_of(".recent").expect("no shelf");
    assert!(
        (height as f64 - want).abs() <= slack(want),
        "a row is {height} tall and the app's is {want}",
    );
}

/// **The Information window lists what the app's lists, in the app's order.**
///
/// The rows a document produces rather than all ten: a paper with no
/// `/Subject` has no Subject row in either reader, so the fixture's own answer
/// is the question. What is compared is the labels — the values are the
/// document's and the two renderers read them out of the same bytes.
///
/// `Made with`, `Written by` and the two dates are absent from the book
/// fixture and so are absent from both sides. That is the fixture's shape and
/// not a gap; `read_details` in `pdfium.rs` carries all ten.
#[test]
fn the_information_window_says_what_the_app_s_says() {
    let mut reader = reader();
    let app = app();
    let document = &app["document"];

    reader.click(".chip.title");
    // The last item of the menu. The inventory counts the rule between it and
    // Copy path as a row of its own and `.menu-item` does not, which is the
    // same difference `every_menu_lists_what_the_app_s_lists` reads around.
    let last = reader.text_all(".menu.document .menu-item").len() - 1;
    reader.click_nth(".menu.document .menu-item", last);

    assert_eq!(
        reader.text_all(".details-window .window-title"),
        vec![renamed(
            document["title"].as_str().unwrap_or_default().to_string()
        )],
        "what the window is called",
    );
    assert_eq!(
        reader.text_all(".details-label"),
        document["fields"]
            .as_array()
            .expect("the window's rows")
            .iter()
            .map(|row| row.as_str().unwrap_or_default().to_string())
            .collect::<Vec<_>>(),
        "the rows",
    );
}

/// **The theme editor asks for what the app's asks for, and says the same
/// things about it.**
///
/// Both halves matter and the second is the one a comparison of labels would
/// miss: a colour called "Accent" with no sentence under it is a field whose
/// whole meaning the reader has to guess. Eight fields, eight notes — one of
/// which is empty, because a Name needs none — and the two buttons.
#[test]
fn the_theme_editor_asks_the_app_s_questions() {
    // On a theme that recolours, because the editor shows the Links field only
    // for one, and the app's editor had it always.
    let mut reader = Reader::open_with(
        &Reader::book(),
        Options {
            width: 1280,
            height: 860,
            theme: Some(1),
            system_font: cfg!(target_os = "macos"),
            ..Default::default()
        },
    );
    let app = app();
    let editor = &app["editor"];

    reader.press_chord("mod+,");
    reader.click_nth(".nav-item", 1);
    // The buttons are under fifteen theme cards, which is below the foot of
    // the pane at the size the fixture was taken at — in both readers. A
    // browser's `.click()` reaches an element wherever it is; a pointer has to
    // be able to see it, so the pane is scrolled first. Nothing about the port
    // is being worked around here: this is the gesture a reader makes.
    reader.wheel_over(".window-pane", 600.0);
    reader.click(".pane-actions button");

    assert_eq!(
        reader.text_all(".pane-group").last().cloned(),
        Some(editor["heading"].as_str().unwrap_or_default().to_string()),
        "what the editor calls itself",
    );

    let rows = editor["fields"].as_array().expect("the editor's fields");
    let labels: Vec<String> = rows
        .iter()
        .map(|row| row["label"].as_str().unwrap_or_default().to_string())
        .collect();
    let notes: Vec<String> = rows
        .iter()
        .map(|row| row["note"].as_str().unwrap_or_default().to_string())
        .collect();

    // The editor is written into the pane *below* Appearance's own three
    // switches, in both readers — so what is compared is the tail of the
    // pane's fields. The three above it are the Appearance page's and are
    // checked as such by `the_settings_window_has_the_app_s_pages`.
    let tail = |mut all: Vec<String>, want: usize| -> Vec<String> {
        assert!(all.len() >= want, "the editor is not open: {all:?}");
        all.split_off(all.len() - want)
    };
    assert_eq!(
        tail(reader.text_all(".field-label"), labels.len()),
        labels,
        "the fields",
    );
    // A field with no note draws no note in either reader, so the empty one is
    // taken out of both lists rather than compared against nothing.
    let notes: Vec<String> = notes.into_iter().filter(|note| !note.is_empty()).collect();
    assert_eq!(
        tail(reader.text_all(".field-note"), notes.len()),
        notes,
        "what each field says about itself",
    );
    assert_eq!(
        reader.text_all(".pane-actions button"),
        editor["actions"]
            .as_array()
            .expect("the editor's buttons")
            .iter()
            .map(|row| row.as_str().unwrap_or_default().to_string())
            .collect::<Vec<_>>(),
        "the buttons under it",
    );
}

/// **The three things the app says over a page.**
///
/// The way back to a toolbar that has been put away, what a dragged file is
/// told, and the page number while a scroll is running. None of them is part
/// of the chrome and all three are words a reader reads — and the first is the
/// one that matters most, because it names the only way back.
#[test]
fn what_the_app_says_over_a_page_is_said_here_too() {
    // **The pill is asked for here**, which is the one place this test parts
    // company with the fixture. The app showed it by default; this reader does
    // not any more — a count that appears of its own accord over the middle of
    // the page covers the thing it describes, and the scrollbar says the same
    // without words. What it *says* when it is up is still the app's, which is
    // what this test is about.
    let mut reader = Reader::open_with(
        &Reader::book(),
        Options {
            width: 1280,
            height: 860,
            settings: vec![("show_page_pill".into(), serde_json::json!(true))],
            system_font: cfg!(target_os = "macos"),
            ..Default::default()
        },
    );
    let app = app();
    let overlay = &app["overlay"];
    let want = |key: &str| overlay[key].as_str().unwrap_or_default().to_string();
    let one = |reader: &Reader, selector: &str| {
        reader
            .text_all(selector)
            .first()
            .cloned()
            .unwrap_or_default()
    };

    reader.press_chord("mod+t");
    // The handle is not on screen until somebody reaches for the top edge,
    // which is the app's own rule and the reason it is a handle rather than a
    // button that is always there.
    reader.point_to(640.0, 3.0);
    reader.settle();
    // The same words; the line they are broken over is this app's own, and the
    // fixture records what the retired app *said* rather than how it wrapped.
    assert_eq!(
        one(&reader, ".toolbar-peek").replace('\n', " "),
        want("peek"),
        "the way back",
    );

    // The pill is what a scroll puts up, and it says the same "n of m" the
    // toolbar does. The app's was taken at the top of the document; this one
    // is read the same way, before anything has moved it — and with the
    // toolbar still away, which is the only state the pill exists in:
    // `flash_pill` answers nothing while the bar is on screen, because the bar
    // already says which page this is.
    reader.point_to(640.0, 300.0);
    reader.settle();
    reader.wheel(-10.0);
    reader.settle();
    assert_eq!(one(&reader, ".page-pill"), want("pill"), "the page pill");

    reader.press_chord("mod+t");
    reader.drag_over(true);
    assert_eq!(one(&reader, ".drop-hint"), want("drop"), "a dragged file");
    reader.drag_left();
}

/// **The two large areas of the interface, by the colour actually on them.**
///
/// The twenty-two above are compared name for name and every one of them
/// matched while the start screen stood on the wrong one: `--paper`, the
/// toolbar's own colour, where the app has `--bg`. A whole window of the
/// wrong shade, and nothing that reads a variable could see it — the values
/// were right and what was painted with them was not.
///
/// So these two are read off the pixels. The bar with a document behind it,
/// and the ground the start screen stands on, which is asserted where the
/// start screen is. Between them they are nearly all of the app that is not
/// a page.
#[test]
fn the_chrome_is_painted_the_app_s_colours() {
    let mut reader = reader();
    let want = app()["chrome"]["toolbar"]
        .as_str()
        .expect("the app's bar")
        .to_string();
    let (_, y, _, height) = reader.box_of(".toolbar").expect("no bar");
    let shot = reader.screenshot();
    // Two pixels in from the left edge: the bar's own padding is ten, so this
    // is bar and nothing else whatever is on it.
    let scale = shot.height as f32 / 860.0;
    let pixel = shot.at(2, ((y + height / 2.0) * scale) as u32);
    let got = format!("#{:02x}{:02x}{:02x}", pixel[0], pixel[1], pixel[2]);
    assert_eq!(got, want, "the toolbar");
}

/// **The recolouring, against the app's own — pixel for pixel.**
///
/// `recolor.rs` calls itself a faithful port of `recolorByPixel` and
/// `tests/recolor.rs` holds the shader to it, but the thing it is faithful
/// *to* was never in either comparison: both sides could have been wrong
/// together and the only place it would show is a document. This closes that,
/// which makes it the one test in the file that is about a page rather than
/// about the chrome.
///
/// The fixture is written by `take-recolor.mjs`, which runs the app's own
/// function in WebKit over 525 pixels picked to reach every branch of it — the
/// whole grey ramp, saturated colour, the near-neutrals either side of
/// `COLOUR_FLOOR`, the washes above `WHITE_POINT`, and a few colours a
/// plotting library actually emits.
///
/// Two ramps, named by what wants them. `duotone` is the one a **link** takes,
/// in Moonowl Light's real copper on the white a page that is not recoloured is
/// printed on — so this is also what says the port paints a cross-reference
/// the colour the app paints it. `recolor` is a page put onto a dark theme
/// with the colours on it kept.
///
/// One level out of 255, which is the tolerance the app already holds its own
/// two paths to and the port already holds its two to.
#[test]
fn the_recolouring_is_the_app_s() {
    let raw = include_str!("parity/recolor-fixture.json");
    let fixture: Value = serde_json::from_str(raw).expect("the app's recolouring");
    let bytes = |hex: &str| -> Vec<u8> {
        (0..hex.len() / 2)
            .map(|at| u8::from_str_radix(&hex[at * 2..at * 2 + 2], 16).expect("a byte"))
            .collect()
    };
    let colour = |hex: &str| -> [u8; 3] {
        let bytes = bytes(hex.trim_start_matches('#'));
        [bytes[0], bytes[1], bytes[2]]
    };
    let pixels = bytes(fixture["pixels"].as_str().expect("the page"));

    for ramp in fixture["ramps"].as_array().expect("the ramps") {
        let name = ramp["name"].as_str().unwrap_or_default();
        let want = bytes(ramp["out"].as_str().expect("what the app made of it"));
        let mut got = pixels.clone();
        moonowl::recolor::recolor_cpu(
            &mut got,
            colour(ramp["text"].as_str().expect("ink")),
            colour(ramp["bg"].as_str().expect("paper")),
            ramp["keepColour"]
                .as_bool()
                .expect("whether colour is kept"),
        );

        let (worst, at) = want.iter().zip(&got).enumerate().fold(
            (0i32, 0usize),
            |(worst, at), (index, (a, b))| {
                let off = (*a as i32 - *b as i32).abs();
                if off > worst {
                    (off, index)
                } else {
                    (worst, at)
                }
            },
        );
        let pixel = at / 4 * 4;
        assert!(
            worst <= 1,
            "{name}: off by {worst} levels at pixel {} — in {:?}, the app {:?}, this reader {:?}",
            at / 4,
            &pixels[pixel..pixel + 4],
            &want[pixel..pixel + 4],
            &got[pixel..pixel + 4],
        );
    }
}
