//! Where you were in each document, and what you had open last.
//!
//! This is reading history rather than configuration, so it lives in its own
//! file and never mixes with settings.
//!
//! Like settings, every change here is a read-modify-write of the whole file,
//! and `remember` fires on every pause in a scroll — so it is the one most
//! likely to meet another. `LOCK` serialises them.

use std::fs;
use std::path::{Path, PathBuf};
use std::sync::Mutex;

use serde::{Deserialize, Serialize};

use crate::atomic_write;

pub const LIMIT: usize = 24;

/// How many windows' worth of "what was open" is worth writing down. Nobody
/// reads eight documents at once; the cap is here so that a label left behind
/// by a closed window cannot make the list grow without end.
const OPEN_LIMIT: usize = 8;

static LOCK: Mutex<()> = Mutex::new(());

/// A place the reader put a pin in.
///
/// One per page, deliberately: a mark is "come back here", and a page is the
/// unit somebody means by "here". Keying them by page is what lets the whole
/// feature work without ids — marking a page that is already marked takes the
/// mark off again, which is the same gesture doing the same thing.
#[derive(Debug, Clone, Default, Serialize, Deserialize)]
pub struct Mark {
    pub page: u32,
    #[serde(default)]
    pub offset: f64,
    #[serde(default)]
    pub title: String,
    #[serde(default)]
    pub at: i64,
}

/// The style a highlight's annotation carries in the file — the PDF spec's
/// own four, and nothing this app invents.
#[derive(Debug, Clone, Copy, Default, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "lowercase")]
pub enum HighlightStyle {
    #[default]
    Highlight,
    Underline,
    Strikeout,
    Squiggly,
}

/// Coloured markup the reader drew on a passage.
///
/// This is the journal, not the store — the annotation itself lives in the
/// document once it has been saved there, and on open the file wins: this
/// list is rebuilt from what the file says and kept only for what a file
/// cannot do on its own (surviving a recompile, a document that cannot be
/// written, listing without opening). See `markup-assessment.md`.
///
/// `id` is generated by the caller (the frontend, with `crypto.randomUUID`)
/// the moment a passage is marked, because removing a highlight the reader
/// has not yet saved needs something to name it by before it has a page
/// object of its own. `annotation_id` is that page object's id, filled in
/// once `getAnnotations` has actually read it back out of the file.
#[derive(Debug, Clone, Default, Serialize, Deserialize)]
pub struct Highlight {
    pub id: String,
    pub page: u32,
    /// Four points per run, x then y, run after run, in the page's own PDF
    /// coordinate space. A flat array of numbers rather than an array of
    /// tables, so — unlike `marks` below — this can sit anywhere in the
    /// struct: TOML only makes a table-valued field earn last place, and a
    /// plain array of floats is not one.
    #[serde(default)]
    pub quads: Vec<f64>,
    /// Hex, like a theme's colours, and read the same careful way — never
    /// handed to CSS or trusted without going through a parser that refuses
    /// anything else.
    pub color: String,
    #[serde(default = "one_opacity")]
    pub opacity: f64,
    #[serde(default)]
    pub style: HighlightStyle,
    #[serde(default)]
    pub quote: String,
    #[serde(default)]
    pub at: i64,
    #[serde(default)]
    pub annotation_id: Option<String>,
}

fn one_opacity() -> f64 {
    1.0
}

#[derive(Debug, Clone, Default, Serialize, Deserialize)]
pub struct Entry {
    pub path: String,
    #[serde(default)]
    pub title: String,
    #[serde(default = "one")]
    pub page: u32,
    /// How far into that page the viewport sat, 0.0 to 1.0. Together with the
    /// page number this restores the exact scroll offset at any zoom level.
    #[serde(default)]
    pub offset: f64,
    #[serde(default)]
    pub opened_at: i64,
    /// What that page is called in the document — `/PageLabels` — as the
    /// toolbar said it when the place was written. Empty where it is the
    /// page's own number.
    #[serde(default, skip_serializing_if = "String::is_empty")]
    pub label: String,
    /// These two serialise as arrays of tables, and TOML puts every plain key
    /// of a parent before its tables — so both have to come after every plain
    /// field above, or those fields land inside the last mark instead of on
    /// the entry. Their order relative to *each other* does not matter, only
    /// that neither is above a plain key.
    #[serde(default)]
    pub marks: Vec<Mark>,
    #[serde(default)]
    pub highlights: Vec<Highlight>,
}

fn one() -> u32 {
    1
}

#[derive(Debug, Clone, Default, Serialize, Deserialize)]
pub struct Library {
    /// What was open when the app was last put down, so it can be picked up
    /// again — one path per window, in the order the windows claimed one.
    /// Empty when the reader closed the documents themselves: that is them
    /// saying they have finished, and reopening would be the app arguing.
    ///
    /// A list rather than a path because there is more than one window now.
    /// It was a path, and a file written by that version still reads: see
    /// `one_or_many`. Only the list is ever written.
    ///
    /// Kept here rather than in `settings.toml` because it is not a setting —
    /// it is the other half of what the first line of this file claims to
    /// know. Serialised before `file`, because a TOML table has to come after
    /// every plain key of its parent or it swallows them — and an array of
    /// strings is a plain key, so this still holds.
    #[serde(default, deserialize_with = "one_or_many")]
    pub open: Vec<String>,
    #[serde(default, rename = "file")]
    pub files: Vec<Entry>,
}

/// `open` used to be one path and is now a list of them. A `library.toml`
/// written by the version before this one says `open = "..."`, and reading it
/// as a list of one is the whole of what compatibility costs here — the same
/// answer `theme.rs` gives to a renamed key, and for the same reason: a
/// downgrade that silently eats where you were is worse than a line of code.
fn one_or_many<'de, D>(deserializer: D) -> Result<Vec<String>, D::Error>
where
    D: serde::Deserializer<'de>,
{
    #[derive(Deserialize)]
    #[serde(untagged)]
    enum Shape {
        One(String),
        Many(Vec<String>),
    }
    Ok(match Shape::deserialize(deserializer)? {
        // The old file wrote an empty string for "nothing was open".
        Shape::One(one) if one.is_empty() => Vec::new(),
        Shape::One(one) => vec![one],
        Shape::Many(many) => many,
    })
}

pub fn path(dir: &Path) -> PathBuf {
    dir.join("library.toml")
}

pub fn load(dir: &Path) -> Library {
    read(dir).unwrap_or_default()
}

/// The library as it stands, for a write: a file that is there and will not
/// parse is refused rather than replaced. A write built from nothing kept one
/// entry, and marks kept beside a document live nowhere else. See
/// `settings::read`, which has the same rule for the same reason.
fn read(dir: &Path) -> Result<Library, String> {
    const UNREADABLE: &str =
        "library.toml has a mistake in it, so places and marks are not saved until it is fixed";
    match fs::read_to_string(path(dir)) {
        Ok(body) => toml::from_str(&body).map_err(|_| UNREADABLE.to_string()),
        Err(e) if e.kind() == std::io::ErrorKind::NotFound => Ok(Library::default()),
        Err(_) => Err(UNREADABLE.to_string()),
    }
}

fn save(dir: &Path, library: &Library) -> Result<(), String> {
    let body = toml::to_string_pretty(library).map_err(|e| e.to_string())?;
    atomic_write(&path(dir), body.as_bytes())
}

/// Move a document to the front of the list, keeping the position already
/// recorded for it.
pub fn touch(dir: &Path, file: &str, title: &str, now: i64) -> Result<Library, String> {
    let _guard = crate::config::hold(&LOCK, &path(dir));
    let mut library = read(dir)?;
    let mut entry = take(&mut library, file).unwrap_or_else(|| Entry {
        path: file.to_string(),
        page: 1,
        ..Entry::default()
    });
    if !title.is_empty() {
        entry.title = title.to_string();
    }
    entry.opened_at = now;
    library.files.insert(0, entry);
    // Only an entry with nothing of the reader's in it falls off the end: a
    // bookmark or a highlight is not "recents" data, and the shelf shows the
    // first `LIMIT` whatever is kept behind them. Nor one open in a window
    // now, whose place and marks would otherwise have nowhere to be written.
    let mut seen = 0;
    let open = &library.open;
    library.files.retain(|entry| {
        seen += 1;
        seen <= LIMIT
            || !entry.marks.is_empty()
            || !entry.highlights.is_empty()
            || open.contains(&entry.path)
    });
    save(dir, &library)?;
    Ok(library)
}

pub fn remember(dir: &Path, file: &str, page: u32, offset: f64, label: &str) -> Result<(), String> {
    let _guard = crate::config::hold(&LOCK, &path(dir));
    let mut library = read(dir)?;
    let Some(entry) = library.files.iter_mut().find(|e| e.path == file) else {
        return Ok(());
    };
    if entry.page == page && (entry.offset - offset).abs() < 0.0005 {
        return Ok(());
    }
    entry.page = page;
    entry.offset = offset;
    entry.label = if label == page.to_string() {
        String::new()
    } else {
        label.to_string()
    };
    save(dir, &library)
}

pub fn forget(dir: &Path, file: &str) -> Result<Library, String> {
    let _guard = crate::config::hold(&LOCK, &path(dir));
    let mut library = read(dir)?;
    take(&mut library, file);
    save(dir, &library)?;
    Ok(library)
}

/// Put a pin in a page, or take one out. The same call does both: a page that
/// is already marked is unmarked, which is what pressing the same key twice
/// means everywhere else.
///
/// Returns whether the page ended up marked, and the marks as they now stand.
pub fn toggle_mark(
    dir: &Path,
    file: &str,
    page: u32,
    offset: f64,
    title: &str,
    now: i64,
) -> Result<(bool, Vec<Mark>), String> {
    let _guard = crate::config::hold(&LOCK, &path(dir));
    let mut library = read(dir)?;
    let Some(entry) = library.files.iter_mut().find(|e| e.path == file) else {
        return Err("That document is not in the library.".into());
    };
    let marked = match entry.marks.iter().position(|mark| mark.page == page) {
        Some(at) => {
            entry.marks.remove(at);
            false
        }
        None => {
            entry.marks.push(Mark {
                page,
                offset,
                title: title.to_string(),
                at: now,
            });
            entry.marks.sort_by_key(|mark| mark.page);
            true
        }
    };
    let marks = entry.marks.clone();
    save(dir, &library)?;
    Ok((marked, marks))
}

/// Journal one highlight the reader just drew, ahead of it landing in the
/// document itself — see `Highlight` for why this is a cache rather than the
/// record. Returns the document's highlights as they now stand.
pub fn add_highlight(
    dir: &Path,
    file: &str,
    highlight: Highlight,
) -> Result<Vec<Highlight>, String> {
    let _guard = crate::config::hold(&LOCK, &path(dir));
    let mut library = read(dir)?;
    let Some(entry) = library.files.iter_mut().find(|e| e.path == file) else {
        return Err("That document is not in the library.".into());
    };
    entry.highlights.push(highlight);
    let highlights = entry.highlights.clone();
    save(dir, &library)?;
    Ok(highlights)
}

/// Take one highlight out of the journal, by the id it was given when it was
/// added. Removing it from the document itself is a write of its own — this
/// only stops the journal from offering it back after a recompile.
pub fn remove_highlight(dir: &Path, file: &str, id: &str) -> Result<Vec<Highlight>, String> {
    let _guard = crate::config::hold(&LOCK, &path(dir));
    let mut library = read(dir)?;
    let Some(entry) = library.files.iter_mut().find(|e| e.path == file) else {
        return Err("That document is not in the library.".into());
    };
    entry.highlights.retain(|h| h.id != id);
    let highlights = entry.highlights.clone();
    save(dir, &library)?;
    Ok(highlights)
}

/// Replace a document's marks with what the reader holds. The store is the
/// authority for the length of a session — see `Store::toggle_mark`.
pub fn set_marks(dir: &Path, file: &str, marks: Vec<Mark>) -> Result<(), String> {
    let _guard = crate::config::hold(&LOCK, &path(dir));
    let mut library = read(dir)?;
    let Some(entry) = library.files.iter_mut().find(|e| e.path == file) else {
        return Err("That document is not in the library.".into());
    };
    entry.marks = marks;
    save(dir, &library)
}

/// Replace a document's whole journal of highlights with what the file itself
/// says, the moment it has been read. The journal is never the authority —
/// this is what makes that true: whatever was here before is discarded in
/// favour of what `getAnnotations` just reported.
pub fn set_highlights(dir: &Path, file: &str, highlights: Vec<Highlight>) -> Result<(), String> {
    let _guard = crate::config::hold(&LOCK, &path(dir));
    let mut library = read(dir)?;
    let Some(entry) = library.files.iter_mut().find(|e| e.path == file) else {
        return Err("That document is not in the library.".into());
    };
    entry.highlights = highlights;
    save(dir, &library)
}

/// Give a document the name it calls itself, once the frontend has read it out
/// of the file. A file named `2310.06825v3.pdf` says nothing on a shelf.
pub fn retitle(dir: &Path, file: &str, title: &str) -> Result<Library, String> {
    let _guard = crate::config::hold(&LOCK, &path(dir));
    let mut library = read(dir)?;
    let Some(entry) = library.files.iter_mut().find(|e| e.path == file) else {
        return Ok(library);
    };
    if entry.title == title {
        return Ok(library);
    }
    entry.title = title.to_string();
    save(dir, &library)?;
    Ok(library)
}

/// Note what is open now, so the next launch can pick it up. An empty list
/// means nothing is: the reader closed what they had, and that is a decision
/// to respect.
///
/// The caller holds the live answer — one path per window — and passes the
/// whole of it, because the file is the record of what the app is holding
/// rather than a log of what each window did.
pub fn set_open(dir: &Path, files: &[String]) -> Result<(), String> {
    let _guard = crate::config::hold(&LOCK, &path(dir));
    let mut library = read(dir)?;
    let mut wanted: Vec<String> = Vec::new();
    for file in files {
        // The same document open in two windows is one document to reopen.
        if !file.is_empty() && !wanted.contains(file) {
            wanted.push(file.clone());
        }
    }
    wanted.truncate(OPEN_LIMIT);
    if library.open == wanted {
        return Ok(());
    }
    library.open = wanted;
    save(dir, &library)
}

/// Drop entries whose file is gone, so the recents list stays honest — and
/// with them a remembered document that is no longer there.
pub fn prune(library: &Library) -> Library {
    Library {
        open: library
            .open
            .iter()
            .filter(|file| Path::new(file).is_file())
            .cloned()
            .collect(),
        files: library
            .files
            .iter()
            .filter(|entry| Path::new(&entry.path).is_file())
            .cloned()
            .collect(),
    }
}

fn take(library: &mut Library, file: &str) -> Option<Entry> {
    let index = library.files.iter().position(|e| e.path == file)?;
    Some(library.files.remove(index))
}

#[cfg(test)]
mod tests {
    use super::*;

    fn scratch(name: &str) -> PathBuf {
        let dir = std::env::temp_dir().join(format!("moonowl-lib-{}-{name}", std::process::id()));
        let _ = fs::remove_dir_all(&dir);
        fs::create_dir_all(&dir).expect("scratch");
        dir
    }

    #[test]
    fn an_open_document_is_not_pushed_off_the_shelf() {
        let dir = scratch("open-kept");
        let docs: Vec<String> = (0..=LIMIT)
            .map(|n| dir.join(format!("{n}.pdf")).to_string_lossy().to_string())
            .collect();
        touch(&dir, &docs[0], "", 1).expect("touch");
        set_open(&dir, std::slice::from_ref(&docs[0])).expect("open");
        for (n, doc) in docs.iter().enumerate().skip(1) {
            touch(&dir, doc, "", n as i64 + 1).expect("touch");
        }
        assert!(load(&dir).files.iter().any(|e| e.path == docs[0]));
    }

    #[test]
    fn a_marked_document_is_not_pushed_off_the_shelf() {
        let dir = scratch("marked");
        let docs: Vec<String> = (0..=LIMIT)
            .map(|n| dir.join(format!("{n}.pdf")).to_string_lossy().to_string())
            .collect();
        touch(&dir, &docs[0], "", 1).expect("touch");
        toggle_mark(&dir, &docs[0], 3, 0.0, "kept", 1).expect("mark");
        for (n, doc) in docs.iter().enumerate().skip(1) {
            touch(&dir, doc, "", n as i64 + 1).expect("touch");
        }
        let library = load(&dir);
        assert_eq!(library.files.len(), LIMIT + 1, "the marked one stays");
        assert_eq!(library.files.last().expect("an entry").path, docs[0]);
        // And the oldest unmarked one is what goes when another arrives.
        let plain = dir.join("plain.pdf").to_string_lossy().to_string();
        touch(&dir, &plain, "", 0).expect("touch");
        let library = load(&dir);
        assert_eq!(library.files.len(), LIMIT + 1);
        assert!(!library.files.iter().any(|e| e.path == docs[1]));
        assert_eq!(library.files.last().expect("an entry").path, docs[0]);
    }

    #[test]
    fn what_was_open_survives_and_shares_the_file_with_the_entries() {
        let dir = scratch("open");
        let doc = dir.join("paper.pdf");
        fs::write(&doc, b"%PDF-1.4\n%%EOF\n").expect("document");
        let doc = doc.to_string_lossy().to_string();

        touch(&dir, &doc, "paper.pdf", 100).expect("touch");
        remember(&dir, &doc, 12, 0.25, "12").expect("remember");
        set_open(&dir, std::slice::from_ref(&doc)).expect("set open");

        // The one thing this file's shape can get wrong: `open` is a plain key
        // and `file` is an array of tables, and TOML puts every plain key of a
        // parent before its tables. Written the other way round, `open` lands
        // inside the last entry and comes back empty. An array of strings is
        // still a plain key, so widening it did not move that line.
        let back = load(&dir);
        assert_eq!(back.open, vec![doc.clone()]);
        assert_eq!(back.files.len(), 1);
        assert_eq!(back.files[0].page, 12);

        set_open(&dir, &[]).expect("clear open");
        assert!(load(&dir).open.is_empty());
        assert_eq!(load(&dir).files.len(), 1, "clearing it kept the history");
    }

    #[test]
    fn two_windows_worth_of_open_documents_round_trip() {
        let dir = scratch("open-many");
        let one = dir.join("one.pdf");
        let two = dir.join("two.pdf");
        fs::write(&one, b"%PDF-1.4\n%%EOF\n").expect("document");
        fs::write(&two, b"%PDF-1.4\n%%EOF\n").expect("document");
        let one = one.to_string_lossy().to_string();
        let two = two.to_string_lossy().to_string();

        // The same document in two windows is one document to reopen, and the
        // order the windows claimed them in is the order they come back.
        set_open(&dir, &[one.clone(), two.clone(), one.clone()]).expect("set open");
        assert_eq!(load(&dir).open, vec![one.clone(), two.clone()]);

        // And the entries still read back, which is the plain-key-before-tables
        // rule again.
        touch(&dir, &one, "one.pdf", 100).expect("touch");
        assert_eq!(load(&dir).open, vec![one.clone(), two.clone()]);
        assert_eq!(load(&dir).files.len(), 1);
    }

    #[test]
    fn a_library_written_before_there_were_two_windows_still_reads() {
        let dir = scratch("open-old");
        let doc = dir.join("paper.pdf");
        fs::write(&doc, b"%PDF-1.4\n%%EOF\n").expect("document");
        let doc = doc.to_string_lossy().to_string();

        // What the version before this one wrote: `open` as a bare path.
        let body = format!("open = {doc:?}\n\n[[file]]\npath = {doc:?}\npage = 7\n");
        fs::write(path(&dir), body).expect("old library");

        let back = load(&dir);
        assert_eq!(back.open, vec![doc.clone()], "a path is a list of one");
        assert_eq!(back.files[0].page, 7);

        // And an empty string is what that version wrote for "nothing open".
        fs::write(path(&dir), "open = \"\"\n").expect("old library");
        assert!(load(&dir).open.is_empty());
    }

    #[test]
    fn a_mark_is_a_toggle_and_survives_the_file() {
        let dir = scratch("marks");
        let doc = dir.join("book.pdf");
        fs::write(&doc, b"%PDF-1.4\n%%EOF\n").expect("document");
        let doc = doc.to_string_lossy().to_string();
        touch(&dir, &doc, "book.pdf", 100).expect("touch");

        let (marked, marks) = toggle_mark(&dir, &doc, 12, 0.25, "Chapter 2", 100).expect("mark");
        assert!(marked);
        assert_eq!(marks.len(), 1);

        // Out of order in, in order out.
        toggle_mark(&dir, &doc, 4, 0.0, "Chapter 1", 101).expect("mark");
        let pages: Vec<u32> = load(&dir).files[0].marks.iter().map(|m| m.page).collect();
        assert_eq!(pages, vec![4, 12]);

        // The same page again takes the pin out rather than adding a second.
        let (marked, marks) = toggle_mark(&dir, &doc, 12, 0.25, "Chapter 2", 102).expect("unmark");
        assert!(!marked);
        assert_eq!(marks.len(), 1);

        // And the entry's own keys still read back: `marks` is an array of
        // tables, and TOML puts every plain key of a parent before its tables,
        // so anything below it in the struct would land inside the last mark.
        let back = load(&dir);
        assert_eq!(back.files[0].page, 1);
        assert_eq!(back.files[0].title, "book.pdf");
        assert_eq!(back.files[0].opened_at, 100);
        assert_eq!(back.files[0].marks[0].title, "Chapter 1");
    }

    fn highlight(id: &str, page: u32) -> Highlight {
        Highlight {
            id: id.to_string(),
            page,
            quads: vec![10.0, 20.0, 30.0, 20.0, 10.0, 5.0, 30.0, 5.0],
            color: "#ffd600".to_string(),
            opacity: 0.35,
            style: HighlightStyle::Highlight,
            quote: "the quick brown fox".to_string(),
            at: 100,
            annotation_id: None,
        }
    }

    /// The trap the plan calls out by name: an entry carrying both `marks`
    /// and `highlights` — two arrays of tables — has to read back with every
    /// plain field intact, not swallowed into the last table written.
    #[test]
    fn an_entry_with_both_marks_and_highlights_round_trips() {
        let dir = scratch("marks-and-highlights");
        let doc = dir.join("paper.pdf");
        fs::write(&doc, b"%PDF-1.4\n%%EOF\n").expect("document");
        let doc = doc.to_string_lossy().to_string();
        touch(&dir, &doc, "paper.pdf", 100).expect("touch");

        toggle_mark(&dir, &doc, 4, 0.0, "Chapter 1", 101).expect("mark");
        add_highlight(&dir, &doc, highlight("h1", 4)).expect("highlight");
        add_highlight(&dir, &doc, highlight("h2", 9)).expect("highlight");

        let back = load(&dir);
        let entry = &back.files[0];
        // The entry's own plain fields, which a swallowed key would have
        // reset to their defaults.
        assert_eq!(entry.title, "paper.pdf");
        assert_eq!(entry.opened_at, 100);
        assert_eq!(entry.page, 1);
        assert_eq!(entry.marks.len(), 1);
        assert_eq!(entry.marks[0].title, "Chapter 1");
        assert_eq!(entry.highlights.len(), 2);
        assert_eq!(entry.highlights[0].id, "h1");
        assert_eq!(entry.highlights[0].quads.len(), 8);
        assert_eq!(entry.highlights[0].color, "#ffd600");
        assert_eq!(entry.highlights[1].id, "h2");
    }

    #[test]
    fn a_highlight_is_added_and_removed_by_id() {
        let dir = scratch("highlight-add-remove");
        let doc = dir.join("book.pdf");
        fs::write(&doc, b"%PDF-1.4\n%%EOF\n").expect("document");
        let doc = doc.to_string_lossy().to_string();
        touch(&dir, &doc, "book.pdf", 100).expect("touch");

        let highlights = add_highlight(&dir, &doc, highlight("a", 1)).expect("add");
        assert_eq!(highlights.len(), 1);
        let highlights = add_highlight(&dir, &doc, highlight("b", 2)).expect("add");
        assert_eq!(highlights.len(), 2);

        let highlights = remove_highlight(&dir, &doc, "a").expect("remove");
        assert_eq!(highlights.len(), 1);
        assert_eq!(highlights[0].id, "b");

        assert_eq!(load(&dir).files[0].highlights.len(), 1);
    }

    /// The rule the whole journal design rests on: the file wins. Reopening a
    /// document hands back exactly what `getAnnotations` reported, discarding
    /// whatever the journal held before — including a highlight that only
    /// ever lived here and never made it into the file.
    #[test]
    fn opening_a_document_replaces_the_journal_with_what_the_file_says() {
        let dir = scratch("highlight-rebuild");
        let doc = dir.join("draft.pdf");
        fs::write(&doc, b"%PDF-1.4\n%%EOF\n").expect("document");
        let doc = doc.to_string_lossy().to_string();
        touch(&dir, &doc, "draft.pdf", 100).expect("touch");

        add_highlight(&dir, &doc, highlight("stale", 3)).expect("add");
        assert_eq!(load(&dir).files[0].highlights.len(), 1);

        let mut from_file = highlight("h1", 1);
        from_file.annotation_id = Some("42R".to_string());
        set_highlights(&dir, &doc, vec![from_file]).expect("set");

        let back = load(&dir);
        assert_eq!(back.files[0].highlights.len(), 1);
        assert_eq!(back.files[0].highlights[0].id, "h1");
        assert_eq!(
            back.files[0].highlights[0].annotation_id.as_deref(),
            Some("42R")
        );
    }

    #[test]
    fn a_document_that_is_gone_is_not_reopened() {
        let dir = scratch("gone");
        let missing = dir.join("vanished.pdf").to_string_lossy().to_string();
        touch(&dir, &missing, "vanished.pdf", 100).expect("touch");
        set_open(&dir, std::slice::from_ref(&missing)).expect("set open");

        let pruned = prune(&load(&dir));
        assert!(
            pruned.open.is_empty(),
            "a launch would have failed on it every time"
        );
        assert!(pruned.files.is_empty());
    }

    /// The same rule `settings.rs` has: a library that will not parse is
    /// refused, not replaced by a library of one.
    #[test]
    fn a_library_that_will_not_parse_is_not_written_over() {
        let dir = scratch("typo");
        let typo = "[[file]]\npath = \"/a.pdf\"\npage = \n";
        fs::write(path(&dir), typo).expect("write");

        assert!(touch(&dir, "/b.pdf", "b.pdf", 1).is_err());
        assert!(remember(&dir, "/a.pdf", 3, 0.0, "3").is_err());
        assert_eq!(fs::read_to_string(path(&dir)).expect("read"), typo);
    }
}
