//! A folder of TOML files, one per item, some of which ship with the app.
//! Themes and highlight palettes are both kept this way, under one set of
//! rules, so that the two behave alike:
//!
//! - The shipped files are rewritten at every launch. Editing one in the app
//!   saves a copy under a new name instead.
//! - Renaming an item renames its file too, but only when the app chose the
//!   file's name. A file someone named by hand keeps its name.
//! - A file that cannot be read is left out of the list and reported, not
//!   silently skipped.
//!
//! A type opts in by implementing [`Kept`]: its name and id, its colour
//! check, its file format, and the noun used in messages. Everything else is
//! a provided method of the trait.

use std::fs;
use std::path::{Path, PathBuf};

use serde::de::DeserializeOwned;

use crate::atomic_write;

/// One kind of thing kept on a shelf.
pub trait Kept: Clone + PartialEq + DeserializeOwned {
    /// What one is called in a sentence: "theme", "palette".
    const NOUN: &'static str;
    /// The shipped set, `(id, source)`, in the order it is listed in —
    /// generated by `build.rs` from a directory of the crate's own.
    const SHIPPED: &'static [(&'static str, &'static str)];
    /// What every shipped file says on top of it. See
    /// [`Kept::install_built_ins`].
    const BANNER: &'static str;
    /// Why a file that is not one of these is refused on import.
    const NOT_ONE: &'static str;

    fn name(&self) -> &str;
    fn id(&self) -> &str;
    /// Where it lives: the stem of its file, and whether it shipped. Not
    /// stored in the file; set by whoever read or wrote it.
    fn place(&mut self, id: String, built_in: bool);
    fn rename(&mut self, name: String);
    /// Refused before anything is written, with why: a colour the renderer
    /// cannot read is never written, only to be worn in a fallback.
    fn check(&self) -> Result<(), String>;
    /// What a file has to pass to be listed at all. Nothing, by default: a
    /// theme naming a colour the renderer cannot read is listed and worn
    /// with that colour derived, and said once (`Store::complaint`). A
    /// palette has nothing to stand in for a missing swatch, so it refuses
    /// here what [`Kept::check`] refuses.
    fn listable(&self) -> Result<(), String> {
        Ok(())
    }
    /// As its file says it: what [`Kept::save`] writes and Export hands over,
    /// with no banner, which means nothing outside this folder.
    fn to_toml(&self) -> Result<String, String>;

    /// A shipped file as it is written out: the banner, then the source.
    fn shipped(source: &str) -> String {
        format!("{}{source}", Self::BANNER)
    }

    /// Write the shipped set out on every run, so that a built-in changed in
    /// the app changes on disk too, rather than the first install of it
    /// sitting there for ever. Editing a built-in through the app saves a copy
    /// under an id of its own, so nothing a reader made is at stake; a
    /// built-in hand-edited in place is overwritten, deliberately — the
    /// shipped set is the app's to define — and the banner on it says so.
    fn install_built_ins(dir: &Path) {
        if fs::create_dir_all(dir).is_err() {
            return;
        }
        for (id, source) in Self::SHIPPED {
            let path = dir.join(format!("{id}.toml"));
            let wanted = Self::shipped(source);
            // Only when it differs, and through `atomic_write`: this directory
            // is watched, and a plain write has a moment when the file is
            // empty.
            if fs::read_to_string(&path).unwrap_or_default() != wanted {
                let _ = atomic_write(&path, wanted.as_bytes());
            }
        }
    }

    /// All of them, built-ins first in the order their `order` file gives,
    /// then the reader's own by name. A file that will not read is left out
    /// and said: see [`problems`].
    fn load_all(dir: &Path) -> Vec<Self> {
        let mut kept: Vec<Self> = Vec::new();
        let mut refused: Vec<String> = Vec::new();

        for (id, embedded) in Self::SHIPPED {
            // A shipped file edited in place with a mistake in it is worn as
            // shipped, and said: silently, the edit just seemed to do nothing.
            let from_disk = fs::read_to_string(dir.join(format!("{id}.toml")))
                .ok()
                .and_then(|source| match parse::<Self>(id, &source, true) {
                    Ok(one) => Some(one),
                    Err(why) => {
                        refused.push(format!(
                            "{id}.toml could not be read, so the shipped {} is used instead: {why}.",
                            Self::NOUN
                        ));
                        None
                    }
                });
            if let Some(one) = from_disk.or_else(|| parse(id, embedded, true).ok()) {
                kept.push(one);
            }
        }

        let mut custom: Vec<Self> = Vec::new();
        if let Ok(entries) = fs::read_dir(dir) {
            for entry in entries.flatten() {
                let path = entry.path();
                if path.extension().and_then(|e| e.to_str()) != Some("toml") {
                    continue;
                }
                let Some(id) = path.file_stem().and_then(|s| s.to_str()) else {
                    continue;
                };
                if is_built_in::<Self>(id) {
                    continue;
                }
                let read = fs::read_to_string(&path)
                    .map_err(|e| e.to_string())
                    .and_then(|source| parse(id, &source, false));
                match read {
                    Ok(one) => custom.push(one),
                    Err(why) => refused.push(format!(
                        "{id}.toml is not listed, because it could not be read: {why}."
                    )),
                }
            }
        }
        refused.sort();
        PROBLEMS
            .lock()
            .unwrap_or_else(|e| e.into_inner())
            .insert(dir.to_path_buf(), refused);
        custom.sort_by_key(|one| one.name().to_lowercase());
        kept.append(&mut custom);
        kept
    }

    /// Write one to its file, and hand it back as saved: with the id of the
    /// file it is now in, and never built in.
    fn save(dir: &Path, one: &Self) -> Result<Self, String> {
        one.check()?;
        let noun = Self::NOUN;
        if one.name().trim().is_empty() {
            return Err(format!("A {noun} needs a name."));
        }
        // Two of one name in a list are two rows nobody can tell apart.
        if Self::load_all(dir).iter().any(|other| {
            other.id() != one.id() && other.name().trim().eq_ignore_ascii_case(one.name().trim())
        }) {
            return Err(format!(
                "There is already a {noun} called {}.",
                one.name().trim()
            ));
        }
        let mut id = if one.id().trim().is_empty() {
            // A new one never lands on top of one already there. This is the
            // one place a slug is made rather than kept: a *name* is prose and
            // has to become a file name somehow.
            unique_id::<Self>(dir, &slugify(one.name(), noun))
        } else {
            // An id that exists is the stem of the file it lives in — see
            // `path_for` — and slugifying it would write a second file beside
            // a hand-named one.
            one.id().trim().to_string()
        };
        // **Renamed is renamed on the disk too, where the app named the
        // file**: `brownie.toml` saying `name = "Bay Brown"` is a directory
        // nobody can read. A file called `My Theme.toml` was named by the
        // person who wrote it, and this app does not rename somebody else's
        // file — so the old file is only left behind when its stem is the
        // slug of the name it had, which is what this writes and nothing else
        // does.
        let renamed = old_file_name::<Self>(dir, &id)
            .filter(|old| slugify(old, noun) == id && slugify(one.name(), noun) != id)
            .map(|_| unique_id::<Self>(dir, &slugify(one.name(), noun)));
        if is_built_in::<Self>(&id) {
            // Editing a built-in makes a copy rather than shadowing it.
            id = unique_id::<Self>(dir, &format!("{}-custom", slugify(&id, noun)));
        }
        let unnamed =
            || format!("A {noun} cannot be saved under that name — it is not a file name.");
        let path = path_for(dir, &id).ok_or_else(unnamed)?;
        let body = one.to_toml()?;

        // A rename writes the new file and then deletes the old, in that
        // order: a machine that stops between them has both, which is one
        // listed twice, and the other order has none at all.
        let id = match renamed {
            Some(fresh) => {
                let moved = path_for(dir, &fresh).ok_or_else(unnamed)?;
                atomic_write(&moved, body.as_bytes())?;
                let _ = fs::remove_file(&path);
                fresh
            }
            None => {
                atomic_write(&path, body.as_bytes())?;
                id
            }
        };
        let mut saved = one.clone();
        saved.place(id, false);
        Ok(saved)
    }

    /// `base`, or the first of "base 2", "base 3"… that nothing in `all` is
    /// called: what a new one, a copy and an import are named, so that none
    /// is refused for a name the reader did not choose.
    fn free_name(all: &[Self], base: &str) -> String {
        let base = base.trim();
        (1..)
            .map(|n| {
                if n == 1 {
                    base.to_string()
                } else {
                    format!("{base} {n}")
                }
            })
            .find(|name| {
                !all.iter()
                    .any(|one| one.name().trim().eq_ignore_ascii_case(name))
            })
            .unwrap_or_else(|| base.to_string())
    }

    /// A file from elsewhere, added to the reader's own under an id of its
    /// own — never over one already there, and beside one of the same name as
    /// "Nord 2": importing is asking for it to be added. Refused when it is
    /// not one, or names a colour the renderer cannot read.
    fn import(dir: &Path, source: &str) -> Result<Self, String> {
        let mut one: Self = toml::from_str(source).map_err(|_| Self::NOT_ONE.to_string())?;
        one.place(String::new(), false);
        let name = Self::free_name(&Self::load_all(dir), one.name());
        one.rename(name);
        Self::save(dir, &one)
    }

    fn delete(dir: &Path, id: &str) -> Result<(), String> {
        let noun = Self::NOUN;
        if is_built_in::<Self>(id) {
            return Err(format!("Built-in {noun}s cannot be deleted."));
        }
        let path = path_for(dir, id)
            .ok_or_else(|| format!("That is not a {noun} name, so there is nothing to delete."))?;
        if !path.exists() {
            // Not silence: "Deleted X" about one still in the list.
            return Err(format!("{id} is not there to delete."));
        }
        fs::remove_file(path).map_err(|e| e.to_string())
    }
}

/// One read from its source, placed at `id`.
pub(crate) fn parse<T: Kept>(id: &str, source: &str, built_in: bool) -> Result<T, String> {
    let mut one: T = toml::from_str(source).map_err(|e| e.message().to_string())?;
    one.listable()?;
    one.place(id.to_string(), built_in);
    Ok(one)
}

/// The files in a directory that [`Kept::load_all`] could not read, each with
/// why, as of the last time it looked. A file with a typo in it is otherwise
/// simply missing from the list, which is no answer to somebody who wrote one.
static PROBLEMS: std::sync::Mutex<std::collections::BTreeMap<PathBuf, Vec<String>>> =
    std::sync::Mutex::new(std::collections::BTreeMap::new());

pub fn problems(dir: &Path) -> Vec<String> {
    PROBLEMS
        .lock()
        .unwrap_or_else(|e| e.into_inner())
        .get(dir)
        .cloned()
        .unwrap_or_default()
}

/// A name as a file stem: lower case, runs of anything else a dash. `noun`
/// when nothing is left.
pub fn slugify(name: &str, noun: &str) -> String {
    let mut out = String::new();
    let mut dash = false;
    for ch in name.chars() {
        if ch.is_ascii_alphanumeric() {
            out.push(ch.to_ascii_lowercase());
            dash = false;
        } else if !out.is_empty() && !dash {
            out.push('-');
            dash = true;
        }
    }
    let slug = out.trim_matches('-').to_string();
    if slug.is_empty() {
        noun.into()
    } else {
        slug
    }
}

/// Whatever its case: `Nord.toml` is `nord.toml` to APFS, and one of the
/// reader's own named that would be overwritten by the built-in on the next
/// run.
pub fn is_built_in<T: Kept>(id: &str) -> bool {
    T::SHIPPED
        .iter()
        .any(|(name, _)| name.eq_ignore_ascii_case(id))
}

/// What the one in `id`'s file is *currently* called, or nothing when there is
/// no such file. Read rather than remembered: the name in the draft is the new
/// one by the time [`Kept::save`] is asked.
fn old_file_name<T: Kept>(dir: &Path, id: &str) -> Option<String> {
    let source = fs::read_to_string(path_for(dir, id)?).ok()?;
    parse::<T>(id, &source, false)
        .ok()
        .map(|one| one.name().to_string())
}

/// The file one lives in, or nothing if that id could not name one.
///
/// An id **is** a file stem, read off the directory verbatim, so one written
/// by hand is called `My Theme` and not `my-theme`, and everything that goes
/// looking for it uses the name it actually has. Verbatim is not unchecked:
/// it has to name a file in this directory and nothing else — no separators,
/// no walking upwards, nothing empty — and anything else is refused rather
/// than repaired.
pub fn path_for(dir: &Path, id: &str) -> Option<PathBuf> {
    let name = format!("{id}.toml");
    if id.trim().is_empty() || Path::new(&name).file_name() != Some(name.as_ref()) {
        return None;
    }
    Some(dir.join(name))
}

/// A slug nothing in the directory is using yet. `base` comes from
/// [`slugify`], so it is always a name a file can have.
fn unique_id<T: Kept>(dir: &Path, base: &str) -> String {
    let free =
        |id: &str| !is_built_in::<T>(id) && path_for(dir, id).is_some_and(|path| !path.exists());
    if free(base) {
        return base.to_string();
    }
    (2..)
        .map(|n| format!("{base}-{n}"))
        .find(|candidate| free(candidate))
        .expect("a free id")
}
